# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/Land-Property-Server.sln'
  project: '**/Land-Property.API.csproj'

steps:
- task: NuGetToolInstaller@1
  name: 'NuGetToolInstaller'
  displayName: 'NuGet Tool Installer'

- task: NuGetCommand@2
  name: 'NuGetRestore'
  displayName: 'NuGet Restore Package'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

# - task: DotNetCoreCLI@2
#   name: 'Tests'
#   displayName: 'Run Tests'
#   inputs:
#     command: 'test'
#     projects: '$(solution)'
#     arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  name: 'Publish'
  displayName: 'Publish Project'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts'
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '--output $(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Lan-Property-Server'
    publishLocation: 'Container'
