@Land_Property_API_HostAddress  = http://localhost:5011/api
@UserEmail = tester1@mail.com
@PropertySlug = property-slug

### Register new user
POST {{ Land_Property_API_HostAddress }}/auth/register
Accept: application/json
Content-Type: application/json

{
  "name": "Tester 1",
  "email": "tester1@mail.com",
  "password": "12345678",
  "phoneNumber": "081234567890",
  "address": "Jalan Rumah Tester 1 No. 1"
}

### Register new user 2
POST {{ Land_Property_API_HostAddress }}/auth/register
Accept: application/json
Content-Type: application/json

{
  "name": "Tester 2",
  "email": "tester2@mail.com",
  "password": "12345678",
  "phoneNumber": "081234567891",
  "address": "Jalan Rumah Tester 2 No. 2"
}

### Login first for create token for access other API
POST {{ Land_Property_API_HostAddress }}/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "tester2@mail.com",
  "password": "12345678"
}

### Get user by email
GET {{ Land_Property_API_HostAddress }}/user/{{ UserEmail }}
Accept: application/json
Authorization: Bearer _TOKEN_FROM_LOGIN_HERE_

### Get all property types
GET {{ Land_Property_API_HostAddress }}/propertytype
Accept: application/json

### Get all advertisement types
GET {{ Land_Property_API_HostAddress }}/advertisementtype
Accept: application/json

### Get all properties by user
GET {{ Land_Property_API_HostAddress }}/user/properties
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwianRpIjoiYzRhNjc3OGQtZWQ2Zi00ODdmLTgwNGEtYjY4MmE0YTkxYjMwIiwiZXhwIjoxNzM3OTg5OTAzLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMTEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwMTEifQ.d5CzA1ZafznlvfJczkYZB9kYHqwfsvN-pqUYcyk0qx0

### Get all properties
GET {{ Land_Property_API_HostAddress }}/property/search
Accept: application/json

### Get some properties or all by passed count
GET {{ Land_Property_API_HostAddress }}/property/paginate/1/2
Accept: application/json

### Get property by id
GET {{ Land_Property_API_HostAddress }}/property/{{ PropertySlug }}
Accept: application/json

### Create new property
POST {{ Land_Property_API_HostAddress }}/property
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwianRpIjoiYzRhNjc3OGQtZWQ2Zi00ODdmLTgwNGEtYjY4MmE0YTkxYjMwIiwiZXhwIjoxNzM3OTg5OTAzLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMTEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwMTEifQ.d5CzA1ZafznlvfJczkYZB9kYHqwfsvN-pqUYcyk0qx0

{
  "title": "Rumahnya Tester ",
  "address": "Jalan Rumah Tester 2 No. 2",
  "buildingArea": 80,
  "landAreaX": 6,
  "landAreaY": 10,
  "bedroom": 2,
  "bathroom": 2,
  "floor": 2,
  "price": 1250000000,
  "description": "",
  "images": [],
  "userId": 2,
  "buildingTypeId": 3,
  "advertisementTypeId": 2
}

### Update property by id
PUT {{ Land_Property_API_HostAddress }}/property/{{ PropertySlug }}
Accept: application/json
Content-Type: application/json
Authorization: Bearer _TOKEN_FROM_LOGIN_HERE_

{
  "title": "",
  "address": "",
  "buildingArea": 1,
  "landArea": { "x": 0, "y": 0 },
  "bedroom": 1,
  "bathroom": 1,
  "floor": 1,
  "price": 1,
  "description": "",
  "images": [
    ""
  ],
  "userId": 1,
  "buildingTypeId": 1,
  "advertisementTypeId": 1
}

### Delete property by id
DELETE {{ Land_Property_API_HostAddress }}/property/{{ PropertySlug }}
Accept: application/json
Authorization: Bearer _TOKEN_FROM_LOGIN_HERE_
