name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore Land-Property-Server.sln

    # Build the project
    - name: Build the project
      run: dotnet build --configuration Release Land-Property-Server.sln

    # Publish the project
    - name: Publish the project
      run: dotnet publish Land-Property-API/Land-Property.API.csproj --configuration Release --output ./publish

    # Deploy to Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'land-property' # Replace with your Azure App Service name
        slot-name: 'production'
        publish-profile: '<publishData><publishProfile profileName="land-property - Web Deploy" publishMethod="MSDeploy" publishUrl="land-property.scm.azurewebsites.net:443" msdeploySite="land-property" userName="$land-property" userPWD="plCpj3KZ0bB3vYlXLjmQCoPakubw2WnLxWNDDXcwj4o272lxioHhrKqTj11B" destinationAppUrl="https://land-property.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="land-property - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-sg1-089.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="REDACTED" userPWD="REDACTED" destinationAppUrl="https://land-property.azurewebsites.net" SQLServerDBConnectionString="REDACTED" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="land-property - Zip Deploy" publishMethod="ZipDeploy" publishUrl="land-property.scm.azurewebsites.net:443" userName="$land-property" userPWD="plCpj3KZ0bB3vYlXLjmQCoPakubw2WnLxWNDDXcwj4o272lxioHhrKqTj11B" destinationAppUrl="https://land-property.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'
        package: ./publish
